sudo: false

language: scala

scala:
  - 2.10.5
  - 2.11.6

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test &&
    sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success: 
  - sbt ++$TRAVIS_SCALA_VERSION coveralls

